### ISSUE TITLE
AccessViolationException

### ISSUE THREAD

**Issue by NikasZalias** [bugsnag/bugsnag-dotnet#118]
It's kind of rare case, but with more users, I'm getting more error:

This is the full stacktrace:
`System.AccessViolationException · Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Bugsnag.UnhandledException.HandleEvent(Exception exception, bool runtimeEnding)	
Bugsnag.UnhandledException.CurrentDomain_UnhandledException(object sender, UnhandledExceptionEventArgs e)`

Could someone please fix this issue? I haven't reported this earlier but since yesterday I got 7k+ crashes because of this error, I must report this.

**Comment by tomlongridge** [comment]
Hi @NikasZalias - sometimes Bugsnag code appears in exception/error reports because it's in the call stack (handling the error) during the crash: it's not necessarily the cause of the crash. However we'd need some more information to do any further analysis. Could I ask you to get in touch via our Support Team (support@bugsnag.com)?

**Comment by NikasZalias** [comment]
@tomlongridge okay, wrote an email to given address.
