### ISSUE TITLE
sign Bugsnag.dll

### ISSUE THREAD

**Issue by galich** [bugsnag/bugsnag-dotnet#67]
### Expected behavior

NuGet installed packages to provide signed assemblies.

### Observed behavior

app crash when adding NuGet package to a signed app

> System.IO.FileLoadException: 'Could not load file or assembly 'Bugsnag, Version=1.4.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)'

### Steps to reproduce

1. Create signed .NET app (WPF, console, WinForms - doesn't matter)
2. add nuget package Bugsnag
3. build and run

### Version

1.4.0.0

**Comment by PandaWood** [comment]
See the [StrongNamer Project](https://github.com/dsplaisted/strongnamer)

`Most applications in .NET do not need to be strong named. Strong names can also introduce pain because they end up requiring binding redirects. Because of this, many OSS libraries do not strong name their assemblies.`
...
` Simply install the StrongNamer NuGet package, and it will transparently and automatically sign the assemblies you reference as part of the build process`

**Comment by onovotny** [comment]
@PandaWood That guidance is no longer accurate. Please see the current guidance from the .NET Team:

https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming

**Comment by kenmorse** [comment]
Any update on this? Would be great to see something like a `Bugsnag.signed` in NuGet that was a strong-named signed version of the `Bugsnag` package.

**Comment by mattdyoung** [comment]
Hi @kenmorse 

We're planning to take a look into this when priorities allow.

**Comment by yousif-bugsnag** [comment]
[v3.0.0](https://github.com/bugsnag/bugsnag-dotnet/releases/tag/v3.0.0) of `bugsnag-dotnet` has now been released which adds strong-name signing to the `Bugnsag.dll`, `Bugsnag.AspNet.dll`, `Bugsnag.AspNet.Mvc.dll` and `Bugsnag.AspNet.WebApi.dll` assemblies.
